name: CI/CD Pipeline

on:
  push:
    branches: [ main, developer ]
  pull_request:
    branches: [ main, developer ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            g++ \
            valgrind \
            lcov \
            gcovr

      # Build the project
      - name: Build project
        run: make all

      # Run unit tests
      - name: Run unit tests
        run: make run

      # Run Valgrind (only if tests pass)
      - name: Run Valgrind (memory check)
        if: success()
        run: |
          make valgrind || echo "Valgrind found issues (non-fatal)"

      # Generate coverage (only on developer/main)
      - name: Generate coverage report
        if: github.ref == 'refs/heads/developer' || github.ref == 'refs/heads/main'
        run: |
          make coverage

      # Upload coverage as artifact
      - name: Upload coverage report as artifact
        if: github.ref == 'refs/heads/developer' || github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.run_number }}
          path: |
            coverage.txt
            output.html
          retention-days: 7

      # Remove this if you want Valgrind warnings to fail CI
      # - name: Fail on Valgrind issues
      #   if: failure()
      #   run: exit 1