name: CI/CD Pipeline

# Trigger on:
# - Push to developer or main
# - Pull requests targeting developer or main
on:
  push:
    branches:
      - developer
      - main
  pull_request:
    branches:
      - developer
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write  # Needed for test annotations

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better coverage diff (optional)

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            g++ \
            valgrind \
            lcov \
            gcovr \
            libdoctest-dev

      - name: Build project
        run: make all

      - name: Run unit tests
        id: tests
        run: |
          make run || (echo "Tests failed!" && exit 1)

      - name: Run Valgrind (memory check)
        if: always()  # Run even if tests fail
        run: |
          make valgrind || echo "Valgrind found issues (non-fatal for now)"

      - name: Generate coverage report
        if: github.ref == 'refs/heads/developer' || github.ref == 'refs/heads/main'
        run: |
          make coverage

      - name: Upload coverage report as artifact
        if: github.ref == 'refs/heads/developer' || github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.run_number }}
          path: |
            coverage.txt
            output.html
          retention-days: 7

      - name: Fail if Valgrind detects leaks (optional strict mode)
        if: failure()
        run: |
          echo "Valgrind detected memory issues!"
          exit 1